# Use an official MongoDB image as a parent image
FROM mongo:4.4.5

# Define working directory
WORKDIR /data

# Define mountable directory
VOLUME /data/db

# Expose MongoDB port
EXPOSE 27017

# Set command to run when launching the container
CMD ["mongod"]

#Code Written by @Arpit Singh - 19BCG10069